/**
 * Volt HQ — Embedded Pricing Snapshot
 *
 * Hardcoded pricing data from all eight provider adapters.
 * Used as the default data source until a live feed is available.
 *
 * Last updated: March 2026
 * Sources:
 *   - Hyperbolic: https://docs.hyperbolic.xyz/docs/hyperbolic-pricing
 *   - OpenAI: https://openai.com/pricing
 *   - Anthropic: https://docs.anthropic.com/en/docs/about-claude/models
 *   - Akash: https://console-api.akash.network/v1/gpu-prices (live API, median prices)
 *   - Groq: https://groq.com/pricing/
 *   - Together AI: https://www.together.ai/pricing
 *   - DeepInfra: https://deepinfra.com/pricing
 *   - Fireworks AI: https://fireworks.ai/pricing
 */

import type { Offering } from '@volthq/core';

const NOW = '2026-03-06T00:00:00Z';

export const SNAPSHOT_OFFERINGS: Offering[] = [
  // ─── Hyperbolic (DePIN) ───────────────────────────────
  {
    id: 'hyperbolic:deepseek-ai/DeepSeek-V3:FP8:H100-SXM:global',
    providerId: 'hyperbolic',
    providerName: 'Hyperbolic',
    providerType: 'depin',
    model: 'deepseek-ai/DeepSeek-V3',
    modelShort: 'DeepSeek-V3',
    capabilityTier: 1,
    quantization: 'FP8',
    gpuType: 'H100-SXM',
    region: 'global',
    priceInputPerMillion: 0.50,
    priceOutputPerMillion: 1.00,
    pricePerGpuHour: null,
    qualityScore: 0.92,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'hyperbolic:deepseek-ai/DeepSeek-R1:FP8:H100-SXM:global',
    providerId: 'hyperbolic',
    providerName: 'Hyperbolic',
    providerType: 'depin',
    model: 'deepseek-ai/DeepSeek-R1',
    modelShort: 'DeepSeek-R1',
    capabilityTier: 1,
    quantization: 'FP8',
    gpuType: 'H100-SXM',
    region: 'global',
    priceInputPerMillion: 0.50,
    priceOutputPerMillion: 2.00,
    pricePerGpuHour: null,
    qualityScore: 0.92,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'hyperbolic:meta-llama/Llama-3.1-70B-Instruct:FP8:H100-SXM:global',
    providerId: 'hyperbolic',
    providerName: 'Hyperbolic',
    providerType: 'depin',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: 'FP8',
    gpuType: 'H100-SXM',
    region: 'global',
    priceInputPerMillion: 0.40,
    priceOutputPerMillion: 0.40,
    pricePerGpuHour: null,
    qualityScore: 0.85,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'hyperbolic:meta-llama/Llama-3.1-70B-Instruct:BF16:H100-SXM:global',
    providerId: 'hyperbolic',
    providerName: 'Hyperbolic',
    providerType: 'depin',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: 'BF16',
    gpuType: 'H100-SXM',
    region: 'global',
    priceInputPerMillion: 0.55,
    priceOutputPerMillion: 0.55,
    pricePerGpuHour: null,
    qualityScore: 0.88,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'hyperbolic:meta-llama/Llama-3.1-8B-Instruct:FP8:H100-SXM:global',
    providerId: 'hyperbolic',
    providerName: 'Hyperbolic',
    providerType: 'depin',
    model: 'meta-llama/Llama-3.1-8B-Instruct',
    modelShort: 'Llama-8B',
    capabilityTier: 3,
    quantization: 'FP8',
    gpuType: 'H100-SXM',
    region: 'global',
    priceInputPerMillion: 0.06,
    priceOutputPerMillion: 0.06,
    pricePerGpuHour: null,
    qualityScore: 0.76,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },

  // ─── Akash (DePIN) ──────────────────────────────────
  // Pricing derived from live GPU-hour rates via gpuHourToPerToken():
  // H100 SXM5 median $1.57/hr, A100 SXM4 median $1.18/hr
  {
    id: 'akash:meta-llama/Llama-3.1-70B-Instruct:FP8:H100-SXM:global',
    providerId: 'akash',
    providerName: 'Akash',
    providerType: 'depin',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: 'FP8',
    gpuType: 'H100-SXM',
    region: 'global',
    priceInputPerMillion: 3.489,   // $1.57/hr ÷ 180k tok/hr × 1M × 0.4
    priceOutputPerMillion: 8.722,  // $1.57/hr ÷ 180k tok/hr × 1M
    pricePerGpuHour: 1.57,
    qualityScore: 0.85,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'api',
  },
  {
    id: 'akash:meta-llama/Llama-3.1-70B-Instruct:FP8:A100-80GB:global',
    providerId: 'akash',
    providerName: 'Akash',
    providerType: 'depin',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: 'FP8',
    gpuType: 'A100-80GB',
    region: 'global',
    priceInputPerMillion: 5.244,   // $1.18/hr ÷ 90k tok/hr × 1M × 0.4
    priceOutputPerMillion: 13.111, // $1.18/hr ÷ 90k tok/hr × 1M
    pricePerGpuHour: 1.18,
    qualityScore: 0.85,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'api',
  },
  {
    id: 'akash:meta-llama/Llama-3.1-8B-Instruct:FP8:H100-SXM:global',
    providerId: 'akash',
    providerName: 'Akash',
    providerType: 'depin',
    model: 'meta-llama/Llama-3.1-8B-Instruct',
    modelShort: 'Llama-8B',
    capabilityTier: 3,
    quantization: 'FP8',
    gpuType: 'H100-SXM',
    region: 'global',
    priceInputPerMillion: 0.349,   // $1.57/hr ÷ 1.8M tok/hr × 1M × 0.4
    priceOutputPerMillion: 0.872,  // $1.57/hr ÷ 1.8M tok/hr × 1M
    pricePerGpuHour: 1.57,
    qualityScore: 0.76,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'api',
  },
  {
    id: 'akash:meta-llama/Llama-3.1-8B-Instruct:FP8:A100-80GB:global',
    providerId: 'akash',
    providerName: 'Akash',
    providerType: 'depin',
    model: 'meta-llama/Llama-3.1-8B-Instruct',
    modelShort: 'Llama-8B',
    capabilityTier: 3,
    quantization: 'FP8',
    gpuType: 'A100-80GB',
    region: 'global',
    priceInputPerMillion: 0.524,   // $1.18/hr ÷ 900k tok/hr × 1M × 0.4
    priceOutputPerMillion: 1.311,  // $1.18/hr ÷ 900k tok/hr × 1M
    pricePerGpuHour: 1.18,
    qualityScore: 0.76,
    reliabilityScore: 0.5,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'api',
  },

  // ─── Groq (Centralized) ─────────────────────────────
  {
    id: 'groq:meta-llama/Llama-3.1-70B-Instruct:default:unknown:global',
    providerId: 'groq',
    providerName: 'Groq',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.59,
    priceOutputPerMillion: 0.79,
    pricePerGpuHour: null,
    qualityScore: 0.88,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'groq:meta-llama/Llama-3.1-8B-Instruct:default:unknown:global',
    providerId: 'groq',
    providerName: 'Groq',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-8B-Instruct',
    modelShort: 'Llama-8B',
    capabilityTier: 3,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.05,
    priceOutputPerMillion: 0.08,
    pricePerGpuHour: null,
    qualityScore: 0.78,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'groq:mistralai/Mixtral-8x7B-Instruct-v0.1:default:unknown:global',
    providerId: 'groq',
    providerName: 'Groq',
    providerType: 'centralized',
    model: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    modelShort: 'Mixtral-8x7B',
    capabilityTier: 2,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.24,
    priceOutputPerMillion: 0.24,
    pricePerGpuHour: null,
    qualityScore: 0.85,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },

  // ─── Together AI (Centralized) ─────────────────────────
  {
    id: 'together:meta-llama/Llama-3.1-70B-Instruct:default:unknown:global',
    providerId: 'together',
    providerName: 'Together AI',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.88,
    priceOutputPerMillion: 0.88,
    pricePerGpuHour: null,
    qualityScore: 0.88,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'together:meta-llama/Llama-3.1-8B-Instruct:default:unknown:global',
    providerId: 'together',
    providerName: 'Together AI',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-8B-Instruct',
    modelShort: 'Llama-8B',
    capabilityTier: 3,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.18,
    priceOutputPerMillion: 0.18,
    pricePerGpuHour: null,
    qualityScore: 0.78,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'together:deepseek-ai/DeepSeek-V3:default:unknown:global',
    providerId: 'together',
    providerName: 'Together AI',
    providerType: 'centralized',
    model: 'deepseek-ai/DeepSeek-V3',
    modelShort: 'DeepSeek-V3',
    capabilityTier: 1,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.50,
    priceOutputPerMillion: 0.90,
    pricePerGpuHour: null,
    qualityScore: 0.92,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },

  // ─── DeepInfra (Centralized) ────────────────────────────
  {
    id: 'deepinfra:meta-llama/Llama-3.1-70B-Instruct:default:unknown:global',
    providerId: 'deepinfra',
    providerName: 'DeepInfra',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.20,
    priceOutputPerMillion: 0.27,
    pricePerGpuHour: null,
    qualityScore: 0.88,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'deepinfra:meta-llama/Llama-3.1-8B-Instruct:default:unknown:global',
    providerId: 'deepinfra',
    providerName: 'DeepInfra',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-8B-Instruct',
    modelShort: 'Llama-8B',
    capabilityTier: 3,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.03,
    priceOutputPerMillion: 0.05,
    pricePerGpuHour: null,
    qualityScore: 0.78,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'deepinfra:deepseek-ai/DeepSeek-V3:default:unknown:global',
    providerId: 'deepinfra',
    providerName: 'DeepInfra',
    providerType: 'centralized',
    model: 'deepseek-ai/DeepSeek-V3',
    modelShort: 'DeepSeek-V3',
    capabilityTier: 1,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.30,
    priceOutputPerMillion: 0.60,
    pricePerGpuHour: null,
    qualityScore: 0.95,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },

  // ─── Fireworks AI (Centralized) ────────────────────────
  {
    id: 'fireworks:meta-llama/Llama-3.1-70B-Instruct:default:unknown:global',
    providerId: 'fireworks',
    providerName: 'Fireworks AI',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    modelShort: 'Llama-70B',
    capabilityTier: 2,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.70,
    priceOutputPerMillion: 0.70,
    pricePerGpuHour: null,
    qualityScore: 0.88,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'fireworks:meta-llama/Llama-3.1-8B-Instruct:default:unknown:global',
    providerId: 'fireworks',
    providerName: 'Fireworks AI',
    providerType: 'centralized',
    model: 'meta-llama/Llama-3.1-8B-Instruct',
    modelShort: 'Llama-8B',
    capabilityTier: 3,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.10,
    priceOutputPerMillion: 0.10,
    pricePerGpuHour: null,
    qualityScore: 0.78,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'fireworks:deepseek-ai/DeepSeek-R1:default:unknown:global',
    providerId: 'fireworks',
    providerName: 'Fireworks AI',
    providerType: 'centralized',
    model: 'deepseek-ai/DeepSeek-R1',
    modelShort: 'DeepSeek-R1',
    capabilityTier: 1,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.55,
    priceOutputPerMillion: 2.19,
    pricePerGpuHour: null,
    qualityScore: 0.95,
    reliabilityScore: 0.90,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },

  // ─── OpenAI (Centralized) ────────────────────────────
  {
    id: 'openai:gpt-4o:default:unknown:global',
    providerId: 'openai',
    providerName: 'OpenAI',
    providerType: 'centralized',
    model: 'gpt-4o',
    modelShort: 'GPT-4o',
    capabilityTier: 1,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 2.50,
    priceOutputPerMillion: 10.00,
    pricePerGpuHour: null,
    qualityScore: 0.98,
    reliabilityScore: 0.95,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'openai:gpt-4o-mini:default:unknown:global',
    providerId: 'openai',
    providerName: 'OpenAI',
    providerType: 'centralized',
    model: 'gpt-4o-mini',
    modelShort: 'GPT-4o-mini',
    capabilityTier: 2,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 0.15,
    priceOutputPerMillion: 0.60,
    pricePerGpuHour: null,
    qualityScore: 0.92,
    reliabilityScore: 0.95,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },

  // ─── Anthropic (Centralized) ─────────────────────────
  {
    id: 'anthropic:claude-sonnet-4-6:default:unknown:global',
    providerId: 'anthropic',
    providerName: 'Anthropic',
    providerType: 'centralized',
    model: 'claude-sonnet-4-6',
    modelShort: 'Sonnet 4.6',
    capabilityTier: 2,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 3.00,
    priceOutputPerMillion: 15.00,
    pricePerGpuHour: null,
    qualityScore: 0.93,
    reliabilityScore: 0.95,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
  {
    id: 'anthropic:claude-haiku-4-5:default:unknown:global',
    providerId: 'anthropic',
    providerName: 'Anthropic',
    providerType: 'centralized',
    model: 'claude-haiku-4-5',
    modelShort: 'Haiku 4.5',
    capabilityTier: 4,
    quantization: null,
    gpuType: null,
    region: 'global',
    priceInputPerMillion: 1.00,
    priceOutputPerMillion: 5.00,
    pricePerGpuHour: null,
    qualityScore: 0.86,
    reliabilityScore: 0.95,
    latencyP50Ms: null,
    latencyP95Ms: null,
    observationCount: 0,
    status: 'active',
    lastPriceUpdate: NOW,
    lastObservationUpdate: null,
    dataSource: 'manual',
  },
];
